"""add unique for sender and reicever of a friendship

Revision ID: 996612d64e17
Revises: 5b07cc5a050f
Create Date: 2024-07-28 14:33:36.491329

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "996612d64e17"
down_revision: Union[str, None] = "5b07cc5a050f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "friendships_sender_receiver_pkey", "friendships", ["sender_id", "receiver_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "friendships_sender_receiver_pkey", "friendships", type_="unique"
    )
    # ### end Alembic commands ###
